// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeAXFwyUPsug4HGs0ucXLSTB1IPDEMUns',
    appId: '1:704883061744:web:4623ae52ec1e1f1f3da335',
    messagingSenderId: '704883061744',
    projectId: 'laza-ecommerce-31d3f',
    authDomain: 'laza-ecommerce-31d3f.firebaseapp.com',
    storageBucket: 'laza-ecommerce-31d3f.firebasestorage.app',
    measurementId: 'G-QVED25Y09F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAEWlC1IKPfEMDNwNsd-sBL1Mo79RATPY',
    appId: '1:704883061744:android:f9697916862f126a3da335',
    messagingSenderId: '704883061744',
    projectId: 'laza-ecommerce-31d3f',
    storageBucket: 'laza-ecommerce-31d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUctq321aA5td9PMzY1TPVRsN6IS19wBY',
    appId: '1:704883061744:ios:03d1391c89f218a13da335',
    messagingSenderId: '704883061744',
    projectId: 'laza-ecommerce-31d3f',
    storageBucket: 'laza-ecommerce-31d3f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUctq321aA5td9PMzY1TPVRsN6IS19wBY',
    appId: '1:704883061744:ios:03d1391c89f218a13da335',
    messagingSenderId: '704883061744',
    projectId: 'laza-ecommerce-31d3f',
    storageBucket: 'laza-ecommerce-31d3f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeAXFwyUPsug4HGs0ucXLSTB1IPDEMUns',
    appId: '1:704883061744:web:6991de12891b0d223da335',
    messagingSenderId: '704883061744',
    projectId: 'laza-ecommerce-31d3f',
    authDomain: 'laza-ecommerce-31d3f.firebaseapp.com',
    storageBucket: 'laza-ecommerce-31d3f.firebasestorage.app',
    measurementId: 'G-8QY3LE90CX',
  );
}
